server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://gijsiwapfhuspn:701f26300c4a7af766616582c05666a9096fabc761b2095729d4af3240e2be79@ec2-18-214-195-34.compute-1.amazonaws.com:5432/daq8tk62avsqn4
    username: user
    password: senha
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado pra bootcamp / backend